import Footer from '@/components/footer/footer'
import Navbar from '@/components/navbar/navbar'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'our cake',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container'>
        
    
        
        {children}
        
        
        </div>
      
      
      </body>
    </html>
  )
}
